export const loadingSubject = [
    "================================================================================",
    "                            LOADING SUBJECT DATA",
    "================================================================================",
]

export const subjectInfo = [
    "================================================================================",
    " WARNING: SUBJECT INFORMATION PARTIALLY CORRUPTED.",
    "================================================================================",
    "                             SUBJECT: LEE MEASURES",
    "                    CURRENT STATUS: TECH LEAD & SNR. SFT. ENG.",
    "================================================================================",
    " ",
    "OBSERVATION SUMMARY",
    "--------------------------------------------------------------------------------",
    "Subject exhibits extensive expertise in full-stack development, cloud",
    "infrastructure (AWS, Azure), and continuous integration/continuous deployment",
    "(CI/CD). Demonstrates a proven ability to lead teams and deliver innovative web",
    "and desktop applications. Subject advocates strongly for web standards, usability,",
    "and accessibility, ensuring high-quality user experiences.",
    " ",
    "TECHNICAL CAPABILITIES",
    "--------------------------------------------------------------------------------",
    "- Proficient in Languages & Frameworks: JavaScript (ES5 & ES6, TypeScript, Node,",
    "  React, Express, Angular), Python (pandas, numpy, scipy), C#",
    "- Skilled in Testing: Jest, Testing Library, Cypress, Cucumber",
    "- Adept with Databases: MySQL, TSQL, MongoDB, REST APIs, GraphQL",
    "- Expert in Cloud & DevOps: Azure, AWS, Docker, Terraform, Continuous Integration/",
    "  Continuous Deployment (CI/CD), Infrastructure as a Service (IaaS)",
    "- Competent in Web Development: HTML, CSS (SASS, SCSS), Accessibility, UX Design",
    "- Utilizes Tools: Anaconda, MsSQL",
    " ",
    "ADDITIONAL ABILITIES",
    "--------------------------------------------------------------------------------",
    "- Project Scoping: Analyzes existing solutions and produces comprehensive proposals,",
    "  including architectures and timelines.",
    "- Leadership: Leads project teams, mentors team members, and plans/executed project",
    "  architecture.",
    "- Usability & Accessibility: Possesses deep understanding of UX and accessibility",
    "  standards, with practical implementation experience.",
    " ",
    "PROJECT INVOLVEMENT & ACHIEVEMENTS",
    "--------------------------------------------------------------------------------",
    "- Modernized workflows at Rolls Royce across 4 teams of software engineers and data",
    "  scientists, resulting in increased productivity and collaboration.",
    "- Designed, built, and implemented a tailored on-premise cross-network deployment tool",
    "  at Rolls Royce, enhancing deployment efficiency and security.",
    "- Developed a cloud computing solution for off-site software development for Rolls Royce,",
    "  enabling seamless remote collaboration and development.",
    " ",
    "SECURITY CLEARANCE",
    "--------------------------------------------------------------------------------",
    "- DV (Valid until 08/2024)",
    "- SC (Issued 11/2021)",
    " ",
    "EXPERIENCE LOG",
    "--------------------------------------------------------------------------------",
    " ",
    "1. Senior Full Stack Developer & Tech Lead, Aiimi",
    "   Duration: October 2023 - Present",
    "   Skills Observed: Python, JavaScript (ES5, ES6, TypeScript), DevOps, Azure,",
    "   Jest, MsSQL, TSQL, MySQL, Docker, CSS, HTML, Agile Coaching, Stakeholder",
    "   Management, Numpy, Pandas, Anaconda",
    "   Responsibilities:",
    "   - Leads the consulting team in delivering modernized analytics software and tooling.",
    "   - Upskills team members and introduces new technologies and workflows.",
    "   - Advances customer cloud infrastructure for improved software development and data",
    "     analytics.",
    " ",
    "2. Solutions Architect, Airborne Studios",
    "   Duration: December 2022 - February 2023",
    "   Skills Observed: UML, Architecture Design, Cloud Infrastructure, IaaS, Cloud",
    "   Computing, Database Management, Application Development, Project Scoping",
    "   Responsibilities:",
    "   - Investigates existing solutions and proposes new architectures.",
    "   - Recommends tech stack and team composition for project execution.",
    "   - Develops templated architecture based on user interviews and solution analysis.",
    " ",
    "3. Tech Lead/Senior Software Engineer, Raytheon UK",
    "   Duration: July 2022 - September 2023",
    "   Skills Observed: JavaScript (ES5, ES6, TypeScript), DevOps, Azure, AWS, Cloud",
    "   Computing, Lambda, Accessibility Design, SASS, MongoDB, Docker, Containerization,",
    "   React, Kanban, Architecture Design, MsSQL, NoSQL, Database Design, UX Design,",
    "   Terraform, IaC, Unit Testing, Automated UI Testing, SCSS, CI/CD, Scrum Master,",
    "   Agile",
    "   Responsibilities:",
    "   - Provides architectural guidance and leads technical decisions.",
    "   - Negotiates with stakeholders to ensure project goals are met.",
    "   - Implements containerized applications and infrastructure as code using Terraform.",
    "   - Mentors junior team members and acts as scrum master.",
    " ",
    "4. Project Lead, The Access Group",
    "   Duration: August 2019 - October 2021",
    "   Skills Observed: JavaScript (ES5, ES6, TypeScript), DevOps, Accessibility Design,",
    "   React, Architecture Design, MsSQL, Database Design, UX Design, Unit Testing, CI/CD",
    "   Responsibilities:",
    "   - Leads a team to develop a React project with a C#.NET backend.",
    "   - Provides architectural decisions and training to the development team.",
    "   - Delivers the project successfully, including presenting to customers.",
    " ",
    "5. Developer, The Access Group",
    "   Duration: July 2018 - August 2019",
    "   Skills Observed: JavaScript (ES5, ES6, TypeScript), DevOps, Accessibility Design,",
    "   React, Angular, Unit Testing, Automated UI Testing, SCSS, CI/CD",
    "   Responsibilities:",
    "   - Develops new features for React-based SPAs with C#.NET backends.",
    "   - Writes automated tests and analyzes bug reports.",
    " ",
    "================================================================================",
]



