

export const subjectInfo = [
    "================================================================================",
    "                                 LEE MEASURES",
    "                     Tech Lead | Senior Software Engineer",
    " ",
    "                      07763 504590 ● Lee@getMeasures.dev",
    "                       linkedin.com/in/JustGetMeasures/",
    "================================================================================",
    " ",
    "SUMMARY",
    "________________________________________________________________________________",
    "A dedicated Tech Lead and Senior Software Engineer with extensive",
    "experience in full-stack development, cloud infrastructure (AWS,",
    "Azure), and continuous integration/continuous deployment (CI/CD).",
    "Proven track record in leading teams to deliver innovative web and",
    "desktop applications. Strong advocate for web standards, usability,",
    "and accessibility, ensuring high-quality user experiences.",
    " ",
    "TECHNICAL SKILLS",
    "________________________________________________________________________________",
    "● Languages & Frameworks: JavaScript (ES5 & ES6, TypeScript, Node,",
    "  React, Express, Angular), Python (pandas, numpy, scipy), C#",
    "● Testing: Jest, Testing Library, Cypress, Cucumber",
    "● Databases: MySQL, TSQL, MongoDB, REST APIs, GraphQL",
    "● Cloud & DevOps: Azure, AWS, Docker, Terraform, Continuous",
    "  Integration/Continuous Deployment (CI/CD), Infrastructure as a",
    "  Service (IaaS)",
    "● Web Development: HTML, CSS (SASS, SCSS), Accessibility, UX Design",
    "● Tools: Anaconda, MsSQL",
    " ",
    "ADDITIONAL SKILLS",
    "________________________________________________________________________________",
    "● Project Scoping: Analysed existing solutions and produced",
    "  proposals, including architectures and timelines.",
    "● Leadership: Led project teams, mentored team members, and",
    "  planned/executed project architecture.",
    "● Usability & Accessibility: Deep understanding of UX and",
    "  accessibility standards, with practical implementation experience.",
    " ",
    "KEY PROJECTS & ACHIEVEMENTS",
    "________________________________________________________________________________",
    "● Modernised workflows at Rolls Royce across 4 teams of software",
    "  engineers and data scientists, increasing productivity and",
    "  collaboration.",
    "● Designed, built, and implemented a tailored on-premise cross-",
    "  network deployment tool at Rolls Royce, enhancing deployment",
    "  efficiency and security.",
    "● Designed a cloud computing solution for off-site software",
    "  development for Rolls Royce, enabling seamless remote",
    "  collaboration and development.",
    " ",
    "SECURITY CLEARANCE",
    "________________________________________________________________________________",
    "DV (Valid 08/2024)",
    "SC (Issued 11/2021)",
    " ",
    "EXPERIENCE",
    "________________________________________________________________________________",
    " ",
    "Senior Full Stack Developer & Tech Lead, Aiimi",
    "October 2023 - Present",
    "● Skills: Python, JavaScript (ES5, ES6, TypeScript), DevOps, Azure,",
    "  Jest, MsSQL, TSQL, MySQL, Docker, CSS, HTML, Agile Coaching,",
    "  Stakeholder Management, Numpy, Pandas, Anaconda",
    "● Responsibilities:",
    "  ○ Led the consulting team in delivering modernised analytics",
    "    software and tooling.",
    "  ○ Upskilled team members and introduced new technologies and",
    "    workflows.",
    "  ○ Advanced customer cloud infrastructure for better software",
    "    development and data analytics.",
    " ",
    "Solutions Architect, Airborne Studios",
    "December 2022 - February 2023",
    "● Skills: UML, Architecture Design, Cloud Infrastructure, IaaS, Cloud",
    "  Computing, Database Management, Application Development, Project",
    "  Scoping",
    "● Responsibilities:",
    "  ○ Investigated existing solutions and proposed new architectures.",
    "  ○ Recommended tech stack and team composition for project",
    "    execution.",
    "  ○ Developed templated architecture based on user interviews and",
    "    solution analysis.",
    " ",
    "Tech Lead/Senior Software Engineer, Raytheon UK",
    "July 2022 - September 2023",
    "● Skills: JavaScript (ES5, ES6, TypeScript), DevOps, Azure, AWS, Cloud",
    "  Computing, Lambda, Accessibility Design, SASS, MongoDB, Docker,",
    "  Containerization, React, Kanban, Architecture Design, MsSQL, NoSQL,",
    "  Database Design, UX Design, Terraform, IaC, Unit Testing, Automated",
    "  UI Testing, SCSS, CI/CD, Scrum Master, Agile",
    "● Responsibilities:",
    "  ○ Provided architectural guidance and led technical decisions.",
    "  ○ Negotiated with stakeholders to ensure project goals were met.",
    "  ○ Implemented containerized applications and infrastructure as",
    "    code using Terraform.",
    "  ○ Mentored junior team members and acted as scrum master.",
    " ",
    "Project Lead, The Access Group",
    "August 2019 - October 2021",
    "● Skills: JavaScript (ES5, ES6, TypeScript), DevOps, Accessibility",
    "  Design, React, Architecture Design, MsSQL, Database Design, UX",
    "  Design, Unit Testing, CI/CD",
    "● Responsibilities:",
    "  ○ Led a team to develop a React project with a C#.NET backend.",
    "  ○ Provided architectural decisions and training to the development",
    "    team.",
    "  ○ Delivered the project successfully, including presenting to",
    "    customers.",
    " ",
    "Developer, The Access Group",
    "July 2018 - August 2019",
    "● Skills: JavaScript (ES5, ES6, TypeScript), DevOps, Accessibility",
    "  Design, React, Angular, Unit Testing, Automated UI Testing, SCSS,",
    "  CI/CD",
    "● Responsibilities:",
    "  ○ Developed new features for React-based SPAs with C#.NET backends.",
    "  ○ Wrote automated tests and analysed bug reports.",
    " ",
    "================================================================================",
]